[build]
builder = "nixpacks"

[deploy]
startCommand = "yarn build && yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production" 